- project-template:
    name: check-requirements
    check:
      jobs:
        - requirements-check:
            files:
              - ^tools/.*-requires$
              - ^.*requirements.txt$
              - ^.*requirements-py[2,3].txt$
              - playbooks/requirements-check.yaml
    gate:
      jobs:
        - requirements-check:
            files:
              - ^tools/.*-requires$
              - ^.*requirements.txt$
              - ^.*requirements-py[2,3].txt$
              - playbooks/requirements-check.yaml

- job:
    name: requirements-check
    parent: unittests
    required-projects:
      - openstack/requirements
